# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: NONE

[toolchain]
channel = "1.84.1"
components = ["clippy", "rustfmt"]
targets = ["aarch64-unknown-uefi", "x86_64-unknown-uefi"]
profile = "minimal"
